# Generated by Django 5.1.3 on 2025-04-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_clientefornecedor_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientefornecedor',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('fornecedor', 'Fornecedor')], default='cliente', max_length=20),
        ),
    ]
