# Generated by Django 4.2 on 2025-07-03 03:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0008_alter_produto_icms'),
        ('clientes', '0003_alter_clientefornecedor_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraMercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Compra')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor de Entrada')),
                ('forma_pagamento', models.CharField(choices=[('avista', 'À Vista'), ('aprazo', 'A Prazo'), ('parcelado', 'Parcelado')], default='avista', max_length=20, verbose_name='Forma de Pagamento')),
                ('parcelas', models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendente', max_length=15, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('fornecedor', models.ForeignKey(limit_choices_to={'tipo': 'fornecedor'}, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientefornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Compra de Mercadoria',
                'verbose_name_plural': 'Compras de Mercadorias',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompraMercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.compramercadoria', verbose_name='Compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da Compra',
                'verbose_name_plural': 'Itens da Compra',
            },
        ),
    ]
