# Generated by Django 4.2 on 2025-07-02 21:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_clientefornecedor_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Capital Social')),
                ('data_registro', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Registro')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Capital Social',
                'verbose_name_plural': 'Capital Social',
            },
        ),
        migrations.CreateModel(
            name='CategoriaBem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Bem',
                'verbose_name_plural': 'Categorias de Bens',
            },
        ),
        migrations.CreateModel(
            name='BemPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Bem')),
                ('tipo', models.CharField(choices=[('imovel', 'Imóvel'), ('veiculo', 'Veículo'), ('maquina', 'Máquina'), ('equipamento', 'Equipamento'), ('movel', 'Móvel'), ('utensilio', 'Utensílio'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Bem')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Aquisição')),
                ('data_aquisicao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Aquisição')),
                ('vida_util_anos', models.PositiveIntegerField(default=5, verbose_name='Vida Útil (anos)')),
                ('taxa_depreciacao_anual', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taxa de Depreciação Anual (%)')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série/Identificação')),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('baixado', models.BooleanField(default=False, verbose_name='Baixado')),
                ('data_baixa', models.DateField(blank=True, null=True, verbose_name='Data da Baixa')),
                ('motivo_baixa', models.TextField(blank=True, null=True, verbose_name='Motivo da Baixa')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('parcelas', models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonio.categoriabem', verbose_name='Categoria')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientefornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Bem Patrimonial',
                'verbose_name_plural': 'Bens Patrimoniais',
            },
        ),
        migrations.CreateModel(
            name='AquisicaoBem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aquisicao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Aquisição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor de Entrada')),
                ('forma_pagamento', models.CharField(max_length=50, verbose_name='Forma de Pagamento')),
                ('parcelas', models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquisicoes', to='patrimonio.bempatrimonial', verbose_name='Bem Adquirido')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientefornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Aquisição de Bem',
                'verbose_name_plural': 'Aquisições de Bens',
            },
        ),
    ]
