# Generated by Django 5.1.3 on 2025-04-19 03:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0002_produto_quantidade_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inventario', models.DateField(default=django.utils.timezone.now)),
                ('responsavel', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Inventário de Estoque',
                'verbose_name_plural': 'Inventários de Estoque',
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sistema', models.PositiveIntegerField()),
                ('quantidade_fisica', models.PositiveIntegerField()),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.inventarioestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('documento_ref', models.CharField(blank=True, help_text='Número da NF, pedido ou outro documento de referência', max_length=100, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data'],
            },
        ),
    ]
