# Generated by Django 5.1.3 on 2025-04-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
