# Generated by Django 4.2 on 2025-04-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_remove_produto_icms_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='icms',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='ICMS (%)'),
        ),
    ]
