# Generated by Django 5.1.3 on 2025-04-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_remove_venda_produto_remove_venda_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendente', max_length=15),
        ),
    ]
