# Generated by Django 4.2 on 2025-04-25 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_venda_icms_total_venda_valor_liquido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='icms_total',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='valor_liquido',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='valor_total',
        ),
    ]
